#cloud-config
autoinstall:
  version: 1
  identity:
    realname: Mirabetter PC
    hostname: mira-note
    username: mirabetter
    password: $y$j9T$r6r1R16alKxeCimCCPvsj1$sYHJCqywkGOAuZpH2bdKlJrmDTJ4ENyQw/2h3UnPvX2
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: America/Sao_Paulo
  packages:
  - libreoffice
  - gimp
  - git
  - wget
  - timeshift
  - flameshot
  - tilix
  snaps:
  - name: spotify
    channel: stable
    classic: false
  - name: code
    channel: stable
    classic: true
  - name: intellij-idea-community
    channel: stable
    classic: true
  - name: slack
    channel: stable
    classic: false
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot
  storage:
    layout:
      name: lvm
      match:
        size: largest
  interactive-sections:
  - storage
  late-commands:
  - curtin in-target -- wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - curtin in-target -- dpkg -i /tmp/google-chrome.deb || apt-get -f install -y
  - curtin in-target -- apt-get update
  - curtin in-target -- apt-get install -y apt-transport-https gnupg curl
  - curtin in-target -- curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg
    --dearmor -o /usr/share/keyrings/cloudflare-warp.gpg
  - curtin in-target -- bash -c 'echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp.gpg]
    https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/cloudflare-client.list'
  - curtin in-target -- apt-get update
  - curtin in-target -- apt-get install -y cloudflare-warp
